"""
GROMACS MDP Parameter File Editor and Generator
Parses, edits, validates, and serializes .mdp configuration files for simulation stages.
"""

import os


class MDPEditor:
    """Class to parse and manipulate GROMACS MDP files."""

    @staticmethod
    def parse_mdp(mdp_file_path):
        """Parse MDP file into an ordered key-value dictionary."""
        parameters = {}
        if not os.path.exists(mdp_file_path):
            return parameters

        with open(mdp_file_path, "r", encoding="utf-8", errors="ignore") as f:
            for line in f:
                line_str = line.strip()
                if not line_str or line_str.startswith(";"):
                    continue
                # Remove inline comments
                if ";" in line_str:
                    line_str = line_str.split(";")[0].strip()
                if "=" in line_str:
                    k, v = line_str.split("=", 1)
                    parameters[k.strip()] = v.strip()
        return parameters

    @staticmethod
    def generate_mdp_text(param_dict, title="GROMACS MDP Generated by GROMACS-GUI"):
        """Format dictionary of parameters into MDP file text."""
        lines = [f"; {title}", f"; Generated on GROMACS-GUI", ""]
        
        # Group parameters logically
        run_keys = ["title", "integrator", "dt", "nsteps", "emtol", "emstep"]
        out_keys = ["nstxout-compressed", "nstxout", "nstvout", "nstfout", "nstenergy", "nstlog"]
        nb_keys = ["cutoff-scheme", "nstlist", "ns_type", "rlist", "coulombtype", "rcoulomb", "rvdw", "pme_order", "fourierspacing", "DispCorr"]
        t_keys = ["Tcoupl", "tc-grps", "tau_t", "ref_t"]
        p_keys = ["Pcoupl", "pcoupltype", "tau_p", "ref_p", "compressibility"]
        c_keys = ["continuation", "constraint_algorithm", "constraints", "lincs_iter", "lincs_order", "gen_vel", "gen_temp", "gen_seed", "define"]

        written = set()

        def write_group(group_title, keys):
            group_lines = []
            for k in keys:
                if k in param_dict:
                    group_lines.append(f"{k:<25} = {param_dict[k]}")
                    written.add(k)
            if group_lines:
                lines.append(f"; --- {group_title} ---")
                lines.extend(group_lines)
                lines.append("")

        write_group("Run Control", run_keys)
        write_group("Output Control", out_keys)
        write_group("Neighbor Searching & Electrostatics", nb_keys)
        write_group("Temperature Coupling", t_keys)
        write_group("Pressure Coupling", p_keys)
        write_group("Constraints & Velocity Generation", c_keys)

        # Write any remaining key-values
        other_lines = []
        for k, v in param_dict.items():
            if k not in written:
                other_lines.append(f"{k:<25} = {v}")
        if other_lines:
            lines.append("; --- Additional Parameters ---")
            lines.extend(other_lines)
            lines.append("")

        return "\n".join(lines)

    @staticmethod
    def save_mdp(param_dict, output_path, title="GROMACS MDP Configuration"):
        """Save parameter dictionary to disk as an .mdp file."""
        text = MDPEditor.generate_mdp_text(param_dict, title=title)
        os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(text)
        return output_path

    @staticmethod
    def get_preset(stage="em"):
        """Get default preset dictionaries for EM, NVT, NPT, or Production MD."""
        stage_lower = stage.lower()

        if stage_lower == "em":
            return {
                "integrator": "steep",
                "emtol": "500.0",
                "emstep": "0.01",
                "nsteps": "50000",
                "nstlist": "20",
                "cutoff-scheme": "Verlet",
                "ns_type": "grid",
                "coulombtype": "PME",
                "rcoulomb": "1.0",
                "rvdw": "1.0",
                "pme_order": "4",
                "fourierspacing": "0.12",
                "constraints": "h-bonds",
            }

        elif stage_lower == "nvt":
            return {
                "title": "NVT Equilibration",
                "integrator": "md",
                "dt": "0.002",
                "nsteps": "100",  # short, safe GUI default
                "nstxout-compressed": "5000",
                "nstenergy": "5000",
                "nstlog": "5000",
                "continuation": "no",
                "constraint_algorithm": "lincs",
                "constraints": "h-bonds",
                "cutoff-scheme": "Verlet",
                "nstlist": "20",
                "coulombtype": "PME",
                "rcoulomb": "1.0",
                "rvdw": "1.0",
                "Tcoupl": "V-rescale",
                "tc-grps": "Protein_Ligand Water_and_ions",
                "tau_t": "0.1 0.1",
                "ref_t": "300 300",
                "Pcoupl": "no",
                "gen_vel": "yes",
                "gen_temp": "300",
                "gen_seed": "-1",
                "define": "-DPOSRES",
            }

        elif stage_lower == "npt":
            return {
                "title": "NPT Equilibration",
                "integrator": "md",
                "dt": "0.002",
                "nsteps": "100",  # short, safe GUI default
                "nstxout-compressed": "5000",
                "nstenergy": "5000",
                "nstlog": "5000",
                "continuation": "yes",
                "constraint_algorithm": "lincs",
                "constraints": "h-bonds",
                "cutoff-scheme": "Verlet",
                "nstlist": "20",
                "coulombtype": "PME",
                "rcoulomb": "1.0",
                "rvdw": "1.0",
                "Tcoupl": "V-rescale",
                "tc-grps": "Protein_Ligand Water_and_ions",
                "tau_t": "0.1 0.1",
                "ref_t": "300 300",
                "Pcoupl": "C-rescale",
                "pcoupltype": "isotropic",
                "tau_p": "2.0",
                "ref_p": "1.0",
                "compressibility": "4.5e-5",
                "gen_vel": "no",
                "define": "-DPOSRES",
            }

        elif stage_lower in ["md", "prod", "production"]:
            return {
                "title": "Production MD Simulation",
                "integrator": "md",
                "dt": "0.002",
                "nsteps": "100",  # short, safe GUI default
                "nstxout-compressed": "5000",
                "nstenergy": "5000",
                "nstlog": "5000",
                "continuation": "yes",
                "constraint_algorithm": "lincs",
                "constraints": "h-bonds",
                "cutoff-scheme": "Verlet",
                "nstlist": "20",
                "coulombtype": "PME",
                "rcoulomb": "1.0",
                "rvdw": "1.0",
                "Tcoupl": "V-rescale",
                "tc-grps": "Protein_Ligand Water_and_ions",
                "tau_t": "0.1 0.1",
                "ref_t": "300 300",
                "Pcoupl": "Parrinello-Rahman",
                "pcoupltype": "isotropic",
                "tau_p": "2.0",
                "ref_p": "1.0",
                "compressibility": "4.5e-5",
                "gen_vel": "no",
            }

        return {}
