"""
GROMACS Topology & Structure Construction Utilities
Handles merging receptor and ligand coordinates into complex.gro and auto-updating topol.top.
"""

import os
import re


def merge_gro_files(receptor_gro, ligand_gro, output_gro):
    """
    Merge receptor.gro and ligand.gro into complex.gro.
    Updates atom total count and retains receptor box dimension vectors.
    """
    if not os.path.exists(receptor_gro):
        raise FileNotFoundError(f"Receptor GRO file not found: {receptor_gro}")
    if not os.path.exists(ligand_gro):
        raise FileNotFoundError(f"Ligand GRO file not found: {ligand_gro}")

    with open(receptor_gro, "r", encoding="utf-8", errors="ignore") as f:
        rec_lines = f.readlines()

    with open(ligand_gro, "r", encoding="utf-8", errors="ignore") as f:
        lig_lines = f.readlines()

    if len(rec_lines) < 3 or len(lig_lines) < 3:
        raise ValueError("Invalid GRO file format (less than 3 lines)")

    try:
        rec_count = int(rec_lines[1].strip())
    except ValueError:
        raise ValueError(f"Invalid atom count in receptor GRO: {rec_lines[1]}")

    try:
        lig_count = int(lig_lines[1].strip())
    except ValueError:
        raise ValueError(f"Invalid atom count in ligand GRO: {lig_lines[1]}")

    title = f"Complex (Receptor + Ligand) generated by GROMACS-GUI"
    total_count = rec_count + lig_count

    rec_atom_lines = rec_lines[2:-1]
    lig_atom_lines = lig_lines[2:-1]
    box_line = rec_lines[-1]  # Use receptor box line

    output_lines = [f"{title}\n", f" {total_count}\n"]
    output_lines.extend(rec_atom_lines)
    output_lines.extend(lig_atom_lines)
    if not box_line.endswith("\n"):
        box_line += "\n"
    output_lines.append(box_line)

    os.makedirs(os.path.dirname(os.path.abspath(output_gro)), exist_ok=True)
    with open(output_gro, "w", encoding="utf-8") as f:
        f.writelines(output_lines)

    return output_gro


def update_topology(topol_path, ligand_itp_path, ligand_resname="LIG", count=1):
    """
    Smartly update topol.top topology file to include ligand topology (.itp)
    and add molecule entry in [ molecules ] section.
    """
    if not os.path.exists(topol_path):
        raise FileNotFoundError(f"Topology file not found: {topol_path}")
    if not os.path.exists(ligand_itp_path):
        raise FileNotFoundError(f"Ligand ITP file not found: {ligand_itp_path}")

    itp_filename = os.path.basename(ligand_itp_path)

    with open(topol_path, "r", encoding="utf-8", errors="ignore") as f:
        lines = f.readlines()

    # Check if itp is already included
    itp_include_pattern = f'#include "{itp_filename}"'
    has_itp_include = any(itp_filename in line for line in lines)

    new_lines = []
    inserted_include = False

    # Standard insertion point: after forcefield or posre include
    for i, line in enumerate(lines):
        new_lines.append(line)

        if not has_itp_include and not inserted_include:
            # Look for suitable include position
            if "#include" in line and ("forcefield" in line or "posre" in line or "amber" in line or "charmm" in line):
                # Check if next line is not an include or is a section
                if i + 1 < len(lines) and not lines[i + 1].strip().startswith("#include"):
                    new_lines.append(f'\n; Include ligand topology\n#include "{itp_filename}"\n')
                    inserted_include = True

    if not has_itp_include and not inserted_include:
        # Fallback: insert before [ system ]
        final_lines = []
        for line in new_lines:
            if line.strip().startswith("[ system ]"):
                final_lines.append(f'; Include ligand topology\n#include "{itp_filename}"\n\n')
            final_lines.append(line)
        new_lines = final_lines

    # Check [ molecules ] section
    molecules_idx = -1
    for idx, line in enumerate(new_lines):
        if line.strip().startswith("[ molecules ]"):
            molecules_idx = idx
            break

    ligand_entry_exists = False
    if molecules_idx != -1:
        for idx in range(molecules_idx + 1, len(new_lines)):
            line_str = new_lines[idx].strip()
            if line_str and not line_str.startswith(";"):
                parts = line_str.split()
                if len(parts) >= 1 and parts[0] == ligand_resname:
                    ligand_entry_exists = True
                    break

    if not ligand_entry_exists:
        if molecules_idx != -1:
            new_lines.append(f"{ligand_resname:<15} {count}\n")
        else:
            new_lines.append("\n[ molecules ]\n")
            new_lines.append(f"; Compound        #mols\n")
            new_lines.append(f"Protein_chain_A   1\n")
            new_lines.append(f"{ligand_resname:<15} {count}\n")

    with open(topol_path, "w", encoding="utf-8") as f:
        f.writelines(new_lines)

    return topol_path


def parse_ligand_resname_from_gro(gro_file):
    """Attempt to parse ligand residue name from a GRO file."""
    if not os.path.exists(gro_file):
        return "LIG"
    try:
        with open(gro_file, "r", encoding="utf-8", errors="ignore") as f:
            lines = f.readlines()
            if len(lines) >= 3:
                atom_line = lines[2]
                resname = atom_line[5:10].strip()
                # Clean digit numbers from resname (e.g., 1LIG -> LIG)
                resname = re.sub(r"^\d+", "", resname)
                if resname:
                    return resname
    except Exception:
        pass
    return "LIG"
