#!/usr/bin/env python
"""
Docking visualization references (using PyMOL commands/references).
For actual visualization: load receptor + docked poses in PyMOL,
show binding pocket, highlight ligand, measure distances.
"""
from pathlib import Path

def generate_pymol_script(output_path="pipeline/visualization/dock_visualization.pml"):
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    pml_content = """
# PyMOL visualization script for docking results
# Generated by pipeline/preprocess/dock_visualization_reference.py

# Load receptor
load automd/examples/10gs/10gs_protein.pdb, receptor

# Load best docked complex (with hydrogen-added coordinates)
load test/docking_3x/run_1/best_complex.pdb, docked_complex

# Show receptor as surface
show surface, receptor
color lightblue, receptor

# Show ligand as sticks (from docked pose)
select ligand, resn LIG or resn UNL  # Adjust residue name based on actual docking
show sticks, ligand
color orange, ligand

# Highlight binding pocket residues within 5 Angstrom of ligand
select pocket, (receptor within 5.0 of ligand)
show sticks, pocket
color green, pocket

# Label best energy
label docked_complex, "Best energy: -9.10 kcal/mol"

# Save image
set ray_opaque_background, off
ray 1200, 900
png pipeline/visualization/dock_result.png, dpi=300

# Additional: overlay 3 docking poses for comparison
load test/docking_3x/run_1/docked_1.pdbqt, pose_1
load test/docking_3x/run_2/docked_2.pdbqt, pose_2
load test/docking_3x/run_3/docked_3.pdbqt, pose_3
show sticks, pose_1
show sticks, pose_2
show sticks, pose_3
color red, pose_1
color blue, pose_2
color yellow, pose_3
png pipeline/visualization/dock_3_poses_comparison.png, dpi=300

print("Docking visualization complete. Images saved to pipeline/visualization/")
"""
    Path(output_path).write_text(pml_content)
    print(f"✓ PyMOL visualization script: {output_path}")
    # Reference for actual visualization
    ref = Path(output_path).with_suffix(".md")
    ref.write_text(f"# Docking Visualization Reference (PyMOL)\n"
                   f"Script: {output_path}\n"
                   f"Usage: pymol {output_path}\n"
                   f"Outputs:\n"
                   f"  - dock_result.png (receptor surface + ligand sticks + pocket)\n"
                   f"  - dock_3_poses_comparison.png (3 docking poses overlaid)\n")
    print(f"✓ Visualization reference: {ref}")

if __name__ == "__main__":
    generate_pymol_script()
